apiVersion: apps/v1
kind: Deployment
metadata:
  name: <REPO_NAME>-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <REPO_NAME>
  template:
    metadata:
      labels:
        app: <REPO_NAME>
    spec:
      containers:
        - name: <REPO_NAME>
          image: drdocker108/<REPO_NAME>:<IMAGE_TAG>
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: <REPO_NAME>-service
spec:
  selector:
    app: <REPO_NAME>
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31540
